// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  "aws_project_region": "eu-west-1",
  "aws_appsync_graphqlEndpoint": "https://c2u3mzp44navxpu6hdithtjpf4.appsync-api.eu-west-1.amazonaws.com/graphql",
  "aws_appsync_region": "eu-west-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-3zartnkrrjd3fkma6epbbl7nsy"
};
export default awsmobile;
